#title in header
title: "NTU é¸èª²å°å¹«æ‰‹"

#main info
#owner
owner: "ä¾†è‡ª NTU é¸èª²å°å¹«æ‰‹ é–‹ç™¼è€…çš„è¨Šæ¯ï¼š"
email: test@test.test
info: #"å…©ä½ä¾†è‡ªè‡ºå¤§è³‡è¨Šç³»ä»¥åŠè‡ºå¤§é†«å­¸ç³»çš„å­¸ç”Ÿ"
#description
desc: "æ­å–œä½ æ‰¾åˆ°é€™è£¡ï¼å¿«ä¾†é‚€è«‹å¤§å®¶ä¸‹è¼‰ NTU é¸èª²å°å¹«æ‰‹å§ï¼ğŸ˜"

#menu
menu:
  é—œæ–¼: /About
  ä½¿ç”¨æ•™å­¸: /Usage
  Q&A: /Q&A
  éš±ç§æ¬Šæ”¿ç­–: /Privacy-Policy

#index/main page max show posts (in number)
max_post: 0

# Colors use hex color without #
# Theme color
tcolor: 370617

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Earth
placelink: https://en.wikipedia.org/wiki/Earth
github: https://github.com/weiiiii0622/NTU-Grade-Viewer
linkedin:
twitter:
instagram:

# Misc
nanobar: /js/nanobar.min.js
switch_light: â˜€ï¸
switch_dark: ğŸŒ‘

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io
